name: native_screenshot
description: A simple plugin to take screenshots using native code (iOS & Android).
version: 1.0.0

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.10.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      ios:
        pluginClass: NativeScreenshotPlugin
